# Generated by Django 4.2.17 on 2024-12-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_friendship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Model',
        ),
    ]
