global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['base:8000']
    scheme: 'http'

# rule_files:
#   - 'rules.yml'
