groups:
  - name: alertmanager
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} has been down for more than 1 minute."

      - alert: PostgreDown
        expr: pg_up != 1
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL is down."

      - alert: PostgreSQLHighConnections
        expr: sum by (server) (pg_stat_activity_count) > ((sum by (server) (pg_settings_max_connections) - sum by (server) (pg_settings_superuser_reserved_connections)) * 0.8)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.server }} is over 80% of max Postgres connections."
          description: "{{ $labels.server }} is exceeding 80% of the currently configured maximum Postgres connection limit (current value: {{ $value }})."
