# Generated by Django 4.2.17 on 2024-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='The User doesnt change the bio yet', max_length=500),
        ),
    ]
