# Generated by Django 4.2.17 on 2024-12-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        ('auth_app', '0006_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chat_group',
            field=models.ManyToManyField(blank=True, to='chat_app.chatgroup'),
        ),
    ]
