# Generated by Django 4.2.17 on 2025-01-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_customuser_avatar_customuser_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Offline', max_length=50),
        ),
    ]
